export interface Asset {
  assetDescription: string | null;
  assetId: string;
  assetInfo: string;
  assetInfoType: string;
  assetMask: string | null;
  assetName: string | null;
  assetOwnerName: string | null;
  balanceAsOf: string;
  balanceCostBasis: number;
  balanceCostFrom: string;
  balanceCurrent: number;
  balanceFrom: string;
  balancePrice: number | null;
  balancePriceFrom: string;
  balanceQuantityCurrent: number | null;
  beneficiaryComposition: any | null;
  cognitoId: string;
  creationDate: string;
  currencyCode: string | null;
  deactivateBy: string | null;
  descriptionEstatePlan: string;
  hasInvestment: boolean | null;
  holdings: any | null;
  includeInNetWorth: boolean;
  institutionId: number;
  institutionName: string | null;
  integration: string | null;
  integrationAccountId: string | null;
  isActive: boolean;
  isAsset: boolean;
  isFavorite: boolean;
  isLinkedVendor: boolean | null;
  lastUpdate: string;
  lastUpdateAttempt: string;
  logoName: string | null;
  modificationDate: string;
  nextUpdate: string | null;
  nickname: string;
  note: string | null;
  noteDate: string | null;
  ownership: any | null;
  primaryAssetCategory: string;
  status: string | null;
  statusCode: string | null;
  userInstitutionId: string;
  vendorAccountType: string | null;
  vendorContainer: string | null;
  vendorResponse: string | null;
  vendorResponseType: string;
  wealthAssetType: string;
  wid: string;
} 