export const pizzaMenu: Pizza[] = [
  {
    id: 'margherita',
    name: 'Margherita',
    description: 'Classic Italian pizza with fresh mozzarella, basil, and marinara',
    price: 14.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Fresh Mozzarella', category: 'cheese' },
      { name: 'Fresh Basil', category: 'herbs' },
      { name: 'Extra Virgin Olive Oil', category: 'oil' },
    ],
    size: 'medium',
    category: 'classic',
  },
  {
    id: 'pepperoni',
    name: 'Pepperoni',
    description: "America's favorite with pepperoni and mozzarella cheese",
    price: 16.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Pepperoni', category: 'meat' },
    ],
    size: 'medium',
    category: 'classic',
  },
  {
    id: 'supreme',
    name: 'Supreme',
    description: 'Loaded with pepperoni, sausage, peppers, onions, and mushrooms',
    price: 19.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Pepperoni', category: 'meat' },
      { name: 'Italian Sausage', category: 'meat' },
      { name: 'Bell Peppers', category: 'vegetable' },
      { name: 'Red Onions', category: 'vegetable' },
      { name: 'Mushrooms', category: 'vegetable' },
    ],
    size: 'medium',
    category: 'specialty',
  },
  {
    id: 'meat-lovers',
    name: 'Meat Lovers',
    description: 'For carnivores: pepperoni, sausage, ham, and bacon',
    price: 21.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Pepperoni', category: 'meat' },
      { name: 'Italian Sausage', category: 'meat' },
      { name: 'Ham', category: 'meat' },
      { name: 'Bacon', category: 'meat' },
    ],
    size: 'medium',
    category: 'meat-lovers',
  },
  {
    id: 'hawaiian',
    name: 'Hawaiian',
    description: 'Sweet and savory with ham and pineapple',
    price: 17.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Ham', category: 'meat' },
      { name: 'Pineapple', category: 'vegetable' },
    ],
    size: 'medium',
    category: 'specialty',
  },
  {
    id: 'bbq-chicken',
    name: 'BBQ Chicken',
    description: 'Tangy BBQ sauce with grilled chicken and red onions',
    price: 18.99,
    sauce: { name: 'BBQ Sauce', type: 'bbq' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Grilled Chicken', category: 'meat' },
      { name: 'Red Onions', category: 'vegetable' },
      { name: 'Cilantro', category: 'herbs' },
    ],
    size: 'medium',
    category: 'specialty',
  },
  {
    id: 'veggie-deluxe',
    name: 'Veggie Deluxe',
    description: 'Garden fresh vegetables with bell peppers, mushrooms, and olives',
    price: 17.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Bell Peppers', category: 'vegetable' },
      { name: 'Mushrooms', category: 'vegetable' },
      { name: 'Red Onions', category: 'vegetable' },
      { name: 'Black Olives', category: 'vegetable' },
      { name: 'Roma Tomatoes', category: 'vegetable' },
    ],
    size: 'medium',
    category: 'vegetarian',
  },
  {
    id: 'white-pizza',
    name: 'White Pizza',
    description: 'Creamy ricotta and mozzarella with garlic and herbs',
    price: 16.99,
    sauce: { name: 'Garlic Oil', type: 'oil-based' },
    toppings: [
      { name: 'Ricotta Cheese', category: 'cheese' },
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Fresh Garlic', category: 'vegetable' },
      { name: 'Italian Seasoning', category: 'herbs' },
      { name: 'Parmesan Cheese', category: 'cheese' },
    ],
    size: 'medium',
    category: 'specialty',
  },
  {
    id: 'buffalo-chicken',
    name: 'Buffalo Chicken',
    description: 'Spicy buffalo chicken with ranch drizzle and celery',
    price: 19.99,
    sauce: { name: 'Buffalo Sauce', type: 'tomato-based' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Buffalo Chicken', category: 'meat' },
      { name: 'Red Onions', category: 'vegetable' },
      { name: 'Celery', category: 'vegetable' },
      { name: 'Ranch Drizzle', category: 'sauce' },
    ],
    size: 'medium',
    category: 'specialty',
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    description: 'Feta cheese, olives, sun-dried tomatoes, and fresh herbs',
    price: 18.99,
    sauce: { name: 'Pesto', type: 'pesto' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Feta Cheese', category: 'cheese' },
      { name: 'Kalamata Olives', category: 'vegetable' },
      { name: 'Sun-dried Tomatoes', category: 'vegetable' },
      { name: 'Red Onions', category: 'vegetable' },
      { name: 'Fresh Oregano', category: 'herbs' },
    ],
    size: 'medium',
    category: 'vegetarian',
  },
  {
    id: 'vegan-delight',
    name: 'Vegan Delight',
    description: 'Plant-based cheese with roasted vegetables and fresh basil',
    price: 19.99,
    sauce: { name: 'Marinara', type: 'tomato-based' },
    toppings: [
      { name: 'Vegan Mozzarella', category: 'cheese' },
      { name: 'Roasted Eggplant', category: 'vegetable' },
      { name: 'Roasted Bell Peppers', category: 'vegetable' },
      { name: 'Zucchini', category: 'vegetable' },
      { name: 'Fresh Basil', category: 'herbs' },
      { name: 'Balsamic Glaze', category: 'sauce' },
    ],
    size: 'medium',
    category: 'vegan',
  },
  {
    id: 'four-cheese',
    name: 'Four Cheese',
    description: "A cheese lover's dream with mozzarella, cheddar, parmesan, and provolone",
    price: 17.99,
    sauce: { name: 'Garlic White Sauce', type: 'white' },
    toppings: [
      { name: 'Mozzarella Cheese', category: 'cheese' },
      { name: 'Sharp Cheddar', category: 'cheese' },
      { name: 'Parmesan Cheese', category: 'cheese' },
      { name: 'Provolone Cheese', category: 'cheese' },
      { name: 'Fresh Thyme', category: 'herbs' },
    ],
    size: 'medium',
    category: 'specialty',
  },
];
